auto: true
server: true
permalink: none
baseurl: "projectwww"
prose:
  metadata:
    "_stories": |
      title:    "Title of your article"
      abstract: "Abstract"
    "_stories/projects": |
      name: "Project Name"
      img:  "Project Thumbnail"